name: CI workflow

on:
    push:
        branches: [main]
    pull_request:

jobs:
    backend:
        name: Backend(Python)
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
        steps:
            - name: Download code
              uses: actions/checkout@v4

            - name: Set up python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
                cache: pip
                cache-dependency-path: backend/requirements.txt
            
            
            #update pip first and the ninstall requuirments
            - name: Install dependencies
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
                pip install ruff mypy pytest
            
            
            - name: ruff(using lint)
              run: ruff check .
              continue-on-error: true
            
            - name: mypy(using type check)
              run: mypy app
              continue-on-error: true

            - name: pytest
              run: pytest || true

            

        
    frontend:
        name: Frontend(Vue)
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - name: Download code
              uses: actions/checkout@v4
            

            - name: setup pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 9
        
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                node-version: "24"
                cache: pnpm
                cache-dependency-path: frontend/pnpm-lock.yaml
            
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
              
            - name: runt eslint
              run: pnpm exec eslint . || echo "::Warning:: ESlint was skipped as not installed, add eslint and config to enable this check"
              contihue-on-error: true

            - name: run type check
              run: pnpm exec vue-tsc --noEmit || echo "::Warning:: Type check was skipped as not installed, add vue-tsc and config to enable this check"
              continue-on-error: true
            - name: Vitest
              run: pnpm exec vitest run || echo "::Warning:: Vitest was skipped as not installed, add vitest and config to enable this check"
              continue-on-error: true
              
